### ISSUE TITLE
Can you update for the BC version (14)?

### ISSUE THREAD

**Issue by reget** [AlexanderDeniskin/NAV#1]
Does not compile for 
Microsoft.Dynamics.Nav.OpenXml.Common.DocumentExtensions.'Microsoft.Dynamics.Nav.OpenXml, Version=14.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
You have specified an unknown variable.

AppendElementToOpenXmlElement

Define the variable under 'Global C/AL symbols'.
---------------------------
OK   
---------------------------

Thank you

**Comment by AlexanderDeniskin** [comment]
You can remove this variable and use the following function to append elements:
```
AppendOpenXmlElement(ParentOpenXmlElement : DotNet "'DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.DocumentFormat.OpenXml.OpenXmlElement";ChildOpenXmlElement : DotNet "'DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.DocumentFormat.OpenXml.OpenXmlElement");
    VAR
      ArrOfValues : DotNet "'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Array";
    BEGIN
      ArrOfValues := ArrOfValues.CreateInstance(GETDOTNETTYPE(ChildOpenXmlElement), 1);
      ArrOfValues.SetValue(ChildOpenXmlElement,0);

      ParentOpenXmlElement.Append(ArrOfValues);
    END;
```

**Comment by reget** [comment]
Thank you!
