### ISSUE TITLE
Formating and Autofit not working

### ISSUE THREAD

**Issue by rkaufmann72** [AlexanderDeniskin/NAV#2]
Hi,

I tried to use your object in Business Central 14 and I have some issues with it. Maybe you can help.

1. I don't get Autofit to work. Do you have a code sample on how to use this? Even if I reopen the fine in c/al an use the PostOpenExcel function.

2. Exportring Data with a format string, for example #.###,00 which is a typical german format, the result in excel is completely diffrent.

4. Exporting a textstring with celltype text, that contains only numbers like UPN Codes 4043377269805, are shown in excel as 4,04338E+12. Excel shows formated as text for this cells, but ist shortening the string as if it was a number.

3. Using Allignment on many records in a large excel file (30000 lines), this takes ages, and the client seems to hang.

Do you habe any hints for me?

regards,
Rolf

**Comment by AlexanderDeniskin** [comment]
Hi Rolf,

1. Below is an example of AutoFit.
Provided code will create a file and perform AutoFit for all columns when CreateBookAndOpenExcel() is called.
But if you uncomment two lines of code, the AutoFit for all columns will not be executed, it will be performed only for A column, B column will have custom width and others are unchanged. I have checked it in Nav 2017.

```
CLEAR(xlBuf);

xlBuf.AddColumnPr('Wide column to check column width',FALSE,xlBuf."Cell Type"::Text,'');
xlBuf.AddColumnPr('Short',FALSE,xlBuf."Cell Type"::Text,'');
xlBuf.AddColumnPr(123.45,FALSE,xlBuf."Cell Type"::Number,'NumberFormat: #,##0.00');
xlBuf.AddColumnPr('4043377269805',FALSE,xlBuf."Cell Type"::Text,'');

//xlBuf.SetColumnsProperty('B',xlBuf.Property::Width,150);
xlBuf.CreateBookAndOpenExcel('','Sheet1','',COMPANYNAME,USERID);
//xlBuf.AutoFit('A:A');
```

You can provide me your example if it doesn't help.

2. Try to use '#,##0.00' instead, as in provided example.
Number Format doesn't depend on regional settings.
Also you can try '#,##0.00;-#,##0.00;;@'  - it won't display 0 (BlankZero in Nav).

4. Provided code generates the following file for me (I have German regional settings).
![image](https://github.com/AlexanderDeniskin/NAV/assets/44909052/e7cf1ac3-d19d-41af-8618-89286c18a3db)
Unfortunately, I have no idea why you receive such result.

5. I confirm this, I was able to reproduce it.
It took about 10 minutes to update alignment in file with 3 columns and 30K lines.
I will try to find out if it is possible to improve. I let you know the results, but it may take some time.

Best regards,
Alexander

**Comment by AlexanderDeniskin** [comment]
Hi Rolf,

I have updated text file on GitHub. I reworked  `WriteSheet()`, `WriteAlignment()` and `ChangeCellStyle()` functions, so now it works quite fast - it takes about 1 minute to generate file with 3 columns and 30K rows. 

Best regards,
Alexander
